### ISSUE TITLE
server rendering file-loader assets

### ISSUE THREAD

**Issue by andyfen** [jmurzy/babel-plugin-transform-assets#2]
hello,
I'm trying to use this plugin to render file loader assets (png) for a universal app on the serverside to match webpack. It doesn't seem to be working, when i run the server code i get this error, it doesn't seem to be transforming the assets ?

> SyntaxError: /Users/user/Documents/webpack/server-render2/src/components/react-webpack.png: Unexpected character '�' (1:0)
> 
> > 1 | �PNG
> >     | ^

**component:**
`<img src={require('./react-webpack.png')}/>`

**webpack:**

```
    {
      test: /\.(jpg|png|gif|eot|svg|ttf|woff|woff2)(\?.*)?$/,
      include: [path.resolve('src')],
      loader: 'file',
      query: {
        name: 'assets/[name].[ext]',
      },
    },
```

**server:**

```
// ...
const app = express();

require('babel-core').transform('code', {
  plugins: [['transform-assets', {
              extensions: ['png'],
              name: 'assets/[name].[ext]',
            }]]
});

//...
app.get('*', (req, res) => {
  match(
    { routes, location: req.url },
    (err, redirectLocation, renderProps) => {
```

**Comment by jmurzy** [comment]
Babel's node API doesn't work like that. Notice you're only passing `'code'` in the first parameter, which is just a `string`? 

You should create a .babelrc in your `src/server` and move your config there.

🍺
