### ISSUE TITLE
How can I use the assets after they have been transformed?

### ISSUE THREAD

**Issue by AaronCCWong** [jmurzy/babel-plugin-transform-assets#3]
I am able to get it setup and running but say I have an import that is transformed. How can I use that in my react components on the server side?

**Comment by jmurzy** [comment]
You should be able to render your components as is on the server side.

What's your current setup like, and what are you trying to achieve?

🍺

**Comment by AaronCCWong** [comment]
Hi @jmurzy. Thanks for getting back to me. My components do render on the server side but all the images and styling are gone. I am basically trying to render a single component on the server side. 

Now I realize, I should have no css styling because I am not using my stylesheet anywhere in the component but I would think that the nytLogo would still show up. Instead it tells me that it cannot be found:

`GET http://localhost:3000/nyt-logo.svg?1M0ukYD 500 (Internal Server Error)`

Here is a simplified version of my component:

```
import React from 'react';
import { Link } from 'react-router';

import homeStyle from 'Home.scss';
import nytLogo from '../../../svg/home/nyt-logo.svg';

const Home = () => {
  const renderLandingPageHeader = () => {
    return (
      <Row className="landing-header-wrapper">
        <HeaderContainer />

        <Column xs={12}>
          <h3 className="landing-header">
            This is a header.
          </h3>
        </Column>

        <Column xs= {12}>
          <Link to="/jobs/all" className="browse-btn">
            BROWSE
          </Link>
        </Column>

        <Column xs={12}>
          <Row className="company-sample-wrapper">
            <Column xs={12} className="company-sample-header">
              <h5>
                LOGO
              </h5>
            </Column>

            <Column xs={6} sm={4} md={2} className="logos nyt">
              <img src={nytLogo} className="nyt-logo" />
            </Column>
          </Row>
        </Column>
      </Row>
    );
  };

return (
    <Container fluid className="landing">
      {renderLandingPageHeader()}
    </Container>
  );
};

export default Home;
```

I am using webpack and express with react. I start up my server by using `./node_modules/.bin/babel-node app.js` where `app.js` is my server. 

EDIT**: Nevermind. I solved the problem. Thanks.
