### ISSUE TITLE
Engine requirement too high?

### ISSUE THREAD

**Issue by wldcordeiro** [jmurzy/babel-plugin-transform-assets#6]
You've set the engine requirement to 9.x, that seems high considering 8.x is LTS. I don't quite see what this plugin even needs such a high engine version.

**Comment by sibelius** [comment]
it makes sense

just hit this one

can we move to node 8 LTS? I think node 6 would be cool as well

**Comment by jmurzy** [comment]
Thanks guys! Will do a release later today.
